### ISSUE TITLE
missing dependency [odoo-addons-analyzer]

### ISSUE THREAD

**Issue by ygol** [camptocamp/odoo-repository#4]
Hi Sebastian,
I would like to test your module but I can't find one of the dependencies: "odoo-addons-analyzer".
Is it publicly shared somewhere? TIA

**Comment by extrememicro** [comment]
@ygol 
Maybe? -> https://github.com/sebalix/odoo-addons-analyzer

**Comment by ygol** [comment]
> @ygol Maybe? -> https://github.com/sebalix/odoo-addons-analyzer

Thank you @extrememicro
